yeji424/me-plus

- eslint.config.js
- package-lock.json
- pnpm-lock.yaml
- server/app.js
- server/config/db.js
- server/controllers/planController.js
- server/models/Plan.js
- server/models/PlanAddon.js
- server/package.json
1. endOfLine 에러 무시
2. 요금제 상세 정보 조회 API 구현
3. PlanAddon 스키마 변경 - Object 활용하기
4. Plan 스키마 변경 - Object 활용하기
- DB 조회 성능을 개선하기 위해 embedded object로 스키마 재정의했습니다.
- '데이터가 수정될 일이 적다'는 전제로 작업했습니다.
- 스키마 변경이 필요할 경우 db.js의 MongoDB 함수를 활용하세요.
> Feat: 요금제 상세 정보 조회 API 구현

- client/package.json
- client/src/App.tsx
- client/src/pages/ChatbotPage.tsx
- client/src/pages/ComparePage.tsx
- client/src/pages/PlanTestPage.tsx
- pnpm-lock.yaml
1. 라우팅 구현
2. 페이지 컴포넌트 추가
3. react-router-dom 설치
- react-router-dom으로 기본 라우팅 구조 구현했습니다
- 홈, 챗봇, 맞춤형 요금제 찾기, 요금제 비교 페이지로 구성되어 있습니다
- 허용되지 않은 URL 요청은 `/`로 이동하도록 하였습니다
- 페이지 컴포넌트 파일은 모두 `/src/pages/` 폴더에 있습니다
- `/`는 현재 프롬프트 테스트때문에 PlanChatTester 컴포넌트를 연결해두었습니다
-
> Feat/라우팅 구현

- server/app.js
- server/controllers/planController.js
- server/services/gptFuncDefinitions.js
1. 가이드 기반 필요한 함수 정의
2. 테스트용으로 API에도 함수 등록함
아래 요금제 목록을 반환하는 함수 작성했습니다.
- 무제한 요금제 목록
- OTT 서비스 요금제 목록
- 저렴한 요금제 목록
- 결합형 요금제 목록
- Function calling에 사용해 주십쇼.
> Feat: GPT Function calling에 사용할 함수 정의

- server/services/gptService.js
- server/utils/promptBuilder.js
1. function callings 7개 추가
- getAffordablePlans
- getUnlimitedDataPlans
- getOTTBundlePlans
- requestOTTServiceList
- requestCarouselButtons
- showPlanLists
- requestTextButtons
- openAI에게 function callings용 함수를 정의하고 socket router에 따라 분기처리를 간단히 하였습니다.
- X
> Feat/function callings 정의

- client/src/components/ChatTester.tsx
- server/services/gptService.js
1. .js 누락 추가
2. GPT 모델 오타 수정
3. 테스트 useEffect 추가
- 없습니다
- X
> Fix/js 및 OpenAI 모델 오타 수정

- server/controllers/planController.js
- server/services/gptFuncCallTest.js
- server/services/gptFuncDefinitions.js
1. gpt 요금제 목록 반환하는 함수 정리
- gptFuncCallTest.js 파일 참고
- Responses API 사용하기
> Feat: gpt 요금제 목록 반환하는 함수 정리

- client/src/index.css
- client/src/pages/PlanTestPage.tsx
Feat : 맞춤형 요금제 페이지 메인 구현
- 맞춤형 요금제 연결 메인페이지 입니다.
- 이미지 크기랑 글씨 크기 적당한지 확인해주세요~
> Feat : 맞춤형 요금제 페이지 메인 구현

- client/package.json
- client/src/components/chatbot/BotBubble.tsx
- client/src/components/chatbot/InputBox.tsx
- client/src/components/chatbot/UserBubble.tsx
- client/src/index.css
- client/src/pages/ChatbotPage.tsx
- pnpm-lock.yaml
1. 유저버블, 봇버블, 입력창 컴포 구현
2. 채팅 기능 1차 구현
- react-spring 설치
- 봇 버블 애니메이션 추가
- 유저버블-입력값 연결
- 유저버블 생성 후 1초 후 봇 버블 나타남 
-
- [v] Self-review: commit 이나 오타 없이 코드가 스스로 검토됨
- [v] 로컬에서 모든 기능이 정상 작동함(버그수정 /기능에 대한 테스트)
- [v] 린터 및 포맷터로 코드 정리됨
> Feat: 챗봇 컴포 및 기능 1차 구현

- client/src/components/chatbot/BotBubble.tsx
- client/src/components/chatbot/MarkedText.tsx
- client/src/utils/parseMarkedTextToChars.ts
1. 함수 util 폴더로 이동
2. 렌더링 관련 함수 컴포넌트화
3. useEffect 및 선언 순서 변경
- x
- x
> Refactor/bot bubble 리팩토링

- client/src/components/MainPage/LinkCard.tsx
- client/src/pages/MainPage.tsx
1. 메인페이지 링크 카드 컴포넌트 분리 및 구조 변경
- 메인페이지에서 반복되는 링크 카드 컴포넌트를 분리하고, 구조를 변경
- variant, size props로 디자인 적용
> Refactor/메인페이지 링크카드 컴포넌트 분리

- client/src/components/common/Modal.tsx
- client/src/components/types/Questions.ts
- client/src/components/types/TestResult.ts
- client/src/data/Questions.ts
- client/src/data/TestResult.ts
- client/src/pages/TestPage.tsx
- client/src/pages/TestResultPage.tsx
- client/src/pages/TestWaitingPage.tsx
- 테스트 Header부분 < 누르면 모달 뜨도록 변경
- 사용자 답변에 따라 다른 답변 할수있도록 상황 생성 -> 요금제 맞춰 변경 예정
- 테스트 바랍니다.
> Feat : 테스트페이지 모달 적용 / 테스트 결과 상황 생성

- server/services/gptFuncDefinitions.js
1. api 응답에서 사용할 key값을 자르는 문제 수정
- x
- x
> fix: refineData삭제

- client/src/components/chatbot/BotBubble.tsx
- client/src/components/chatbot/BotBubbleFrame.tsx
- client/src/components/chatbot/FirstCardList.tsx
- client/src/components/chatbot/InitialScreen.tsx
- client/src/components/chatbot/InputBox.tsx
- client/src/components/chatbot/MarkedText.tsx
- client/src/pages/ChatbotPage.tsx
- server/services/gptService.js
1. 채팅안내 컴포넌트 추가
2. 챗봇 아이콘 추가
3. function callings stream 입력 방지로직 추가
- 백엔드에서 function.callings 가 그대로 stream으로 들어가는 현상이 있어서 방지로직 (프론트,백) 추가했습니다.
- x
> Feat/채팅 안내멘트 카드컴포 추가

- server/models/Plan.js
- server/scripts/insertPlans.js
1. plans 에 누락된 프리미엄 addons 등등 추가
-
-
> fix: plans 누락된 필드 추가

- client/src/components/types/TestResult.ts
- client/src/data/Questions.ts
- client/src/data/TestResult.ts
- client/src/pages/TestPage.tsx
- client/src/pages/TestResultPage.tsx
Feat : 요금제 테스트 결과 구현 및 TestResult 데이터 생성
- TestResult에 사용자 응답 별 요금제 적용
- TestResult에 결과 응답 구현
- 동작 확인 완료
- 확인 바랍니다
> Feat : 요금제 테스트 결과 구현 및 TestResult 데이터 생성

- client/src/components/types/TestResult.ts
- client/src/data/TestResult.ts
- client/src/pages/TestResultPage.tsx
TestResultPage안에 있던 혜택 내용 TestResult 데이터 안으로 넣기
{plan.id === 'ott-plus' && '넷플릭스 / 왓챠 제휴 결합'}
{plan.id === 'music-plus' && '지니뮤직 제휴 결합'}
- 이런식으로 따로있던 혜택을 tagLine: '지니뮤직 제휴 결합', 이렇게 넣었습니다!
x
x
> Feat : TestResultPage안에 있던 혜택 내용 TestResult 데이터 안으로 넣기

- client/src/data/TestResult.ts
- client/src/pages/TestPage.tsx
- client/src/pages/TestResultPage.tsx
- client/src/pages/TestWaitingPage.tsx
- client/src/utils/rules.ts
요금제찾기 함수 파일 분리 및 코드 수정
답변기억 방식 수정
-  utils/rules.ts로 함수 분리
- TestPage.ts DB정제
- 기존 localstorage방식을 R.R방식으로 변경
X
X
> Feat : 요금제찾기함수 파일 분리 및 코드 수정

- client/src/hooks/useChatSocket.ts
- client/src/pages/ChatbotPage.tsx
1.챗봇페이지 react.memo, useCallback을 통해 렌더링 최적화
- https://chip-yumberry-7c7.notion.site/21894459a69c80afb024c0854218fb38?source=copy_link
- socket에서 새로운 데이터를 받아와서 재렌더링이 발생했던 현상을 memo와 useCallback을 사용했습니다.
- 추후에 memo같은경우는 삭제하고 react.key로만 관리할 수도 있을 듯 합니다.
-
> feat: useCallback을 통해 렌더링 최적화

- client/src/components/MainPage/LinkCard.tsx
- client/src/components/common/AnimatedWrapper.tsx
1. 서비스 가이드 카드 클릭 이벤트 누락 수정
- AnimatedWrapper에서 onClick() 이벤트도 받도록 설정
-
> Fix: 서비스 가이드 카드 클릭 이벤트 누락 수정

- client/src/App.tsx
- client/src/components/chatbot/FirstCardList.tsx
- client/src/components/chatbot/InputBox.tsx
- client/src/index.css
- client/src/pages/ChatbotPage.tsx
- server/controllers/planSocketController.js
- server/services/gptService.js
- https://chip-yumberry-7c7.notion.site/250623-21b94459a69c809f9a3efb21b9deadad?source=copy_link
- x
> Feat/chatbot page 완성도 다듬기

- client/src/components/testPage/SelectButton.tsx
- client/src/components/testPage/SelectButton3.tsx
- client/src/pages/TestPage.tsx
1. 맞춤형 요금제 찾기 페이지 rounded 적용
- 맞춤형요금제찾기 페이지 버튼 선택 시 border에 rounded, gradation 적용
- x
변경 전
변경 후
> [진행중]Design: 맞춤형요금제찾기 페이지 rounded 적용

- client/package.json
- client/src/pages/TestResultPage.tsx
- pnpm-lock.yaml
> Feat : 폭죽 애니메이션 추가

- client/src/components/common/AnimatedWrapper.tsx
- client/src/components/common/BounceIcon.tsx
- client/src/components/common/FloadingIcon.tsx
- client/src/components/common/IconSwitcher.tsx
- client/src/components/testPage/SelectButton.tsx
- client/src/components/testPage/SelectButton3.tsx
- client/src/index.css
- client/src/pages/TestPage.tsx
1. 테스트 페이지 레이아웃 수정 및 애니메이션 구현
- 무너 애니메이션 구현
- 선택 버튼 애니메이션 구현
- 선택 시 애니메이션 막았다가 재선택 시 다시 활성화
- 꿀팁 동적 요소 적용
- 질문 이동 버튼(<, >) 호버 애니메이션 적용
-
> Feat: 테스트 페이지 애니메이션 구현

- client/src/index.css
- client/src/pages/ServiceGuidePage.tsx
Feat : 서비스가이드-가운데정렬하기
- absolute제거
- index.css top 값 조절
X
> Feat : 서비스가이드-가운데정렬하기

- client/src/pages/TestResultPage.tsx
Feat : 맞춤형요금제 결과페이지 세부조정
- 요금제 이름 상단 마진값 조정
- 요금제 가격 간격 조정
> Feat : 맞춤형요금제 결과페이지 세부조정

- client/src/components/ServiceGuidePage/GuideSlide.tsx
- client/src/index.css
- client/src/pages/ServiceGuidePage.tsx
1. 서비스 가이드 정렬 구조 원상 복구
2. 서비스 가이드 리팩토링
- 서비스 가이드를 가운데 정렬을 하니 페이지네이션이 가려지는 문제가 발생하여 원래대로 원상복구
- 가독성 및 유지보수성 향상을 위해 반복되는 슬라이드 ui를 별도 컴포넌트 GuideSlide.tsx로 분리
- 분리한 GuideSlide.tsx는 의도를 명확히 하기 위해 값을 children으로 받지 않고 props로 받도록 구성
- 수정사항 발생 시 변경이 쉽도록, 슬라이드 데이터 관리(무엇을 보여줄지)와 슬라이드 렌더링(어떻게 보여줄지)을 분리하여 서로에게 영향을 최소화함으로써 유지보수성 향상
- 닫기 아이콘과 Me플러스 시작하기 버튼이 Link태그로 되어있어 의도가 명확하지 않음 → 각각 GuideCloseButton, MePlusStartButton 컴포넌트로 구분하여 의도를 명확하게 함. 구분한 컴포넌트는 가이드 페이지에서의 특화된 컴포넌트라서 재사용 가능성이 낮을 것 같아서 ServiceGuidePage 내부에 구현함
- https://chip-yumberry-7c7.notion.site/21c94459a69c807d9a51ee9d22551998?pvs=73
- x
> Refactor/서비스가이드 리팩토링

- client/src/components/common/Button.tsx
1. 버튼 클릭 영역 축소 문제 해결
- 공통 버튼 컴포넌트에 애니메이션으로 인한 wrapper가 생기면서 클릭이 되는 영역이 축소되는 문제 발생 -> onClick 이벤트를 wrapper에 할당해서 해결
- x
> Fix: 버튼 클릭 영역 축소 문제 해결

- client/src/pages/MainPage.tsx
1. resize 이벤트 리스너 등록하여 자연스럽게 전환되도록 설정
- x
- x
> Style/메인페이지 스타일 조정

- client/src/components/ComparePage/ComparisonResult.tsx
- client/src/pages/TestResultPage.tsx
Feat/외부링크이동 모달수정
외부링크이동 모달수정
X
X
> Feat : 모달 title 변경

- client/src/pages/TestPage.tsx
Feat : 메인돌아가기 버튼 클릭시 0.3초 후 이동
Feat : 메인돌아가기 버튼 클릭시 0.3초 후 이동
X
X
> Feat : 메인돌아가기 버튼 클릭시 0.3초 후 이동

- server/services/gptService.js
- server/socket/socket.js
1. 토큰이 새채팅때 0으로 제대로 초기화 되도록 수정
2. 캐러셀 응답 role user로 되어있던 부분 developer 로 수정
-
-
> fix: 토큰카운트 새채팅때 초기화 되고 누적되도록 수정
